update_date: 2023-07-14
column_names_pg1:
- 区分
- メニュー名称
- 不要
- 卵
- 乳成分
- 小麦
- えび
- かに
- そば
- 落花生
- くるみ
- アーモンド
- あわび
- いか
- いくら
- オレンジ
- カシューナッツ
- キウイフルーツ
- 牛肉
- ごま
- さけ
- さば
- 大豆
- 鶏肉
- バナナ
- 豚肉
- まつたけ
- もも
- やまいも
- りんご
- ゼラチン
column_names_pg2:
- 区分
- メニュー名称
- 卵
- 乳成分
- 小麦
- えび
- かに
- そば
- 落花生
- くるみ
- アーモンド
- あわび
- いか
- いくら
- オレンジ
- カシューナッツ
- キウイフルーツ
- 牛肉
- ごま
- さけ
- さば
- 大豆
- 鶏肉
- バナナ
- 豚肉
- まつたけ
- もも
- やまいも
- りんご
- ゼラチン
